Superarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.decorators.cache import cache_page
from django.views.generic import RedirectView

from commodity.views import show

urlpatterns = [
    url(r'^$', cache_page(3600)(show)),  # 缓存到redis中首页
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('haystack.urls')),  # 全文搜索框架
    url(r'ckeditor', include("ckeditor_uploader.urls")),  # 用户上传的富文本域
    url(r'^user/', include('user.urls', namespace='user')),   # 用户模块
    url(r'^com/', include('commodity.urls', namespace='com')),   # 商品模块
    url(r'^car/', include('shoppingTrolley.urls', namespace='shop')),  # 购物车模块
    url(r'^add/', include('orderForm.urls', namespace='add')),  # 订单模块
    url(r'^favicon.ico$', RedirectView.as_view(url=r'static/favicon.ico'))
]

apps/commodity/urls.py
from django.conf.urls import url, include

from commodity.views import show, category, detail

urlpatterns = [
    url(r'^show/$', show, name='首页'),
    url(r'^category/(?P<id>\d+)/(?P<order>\d+)/$', category, name='商店'),
    url(r'^detail/(?P<id>\d+)/$', detail, name='详情'),
]

apps/orderForm/urls.py
from django.conf.urls import url
from orderForm.views import address, gladd, amendSite, deleteAlter, Alter, submit, notarize, orderForm, seve, pay, \
    pay_all

urlpatterns = [
    url(r'^address/$', address, name='添加地址'),
    url(r'^gladd/$', gladd, name='地址'),
    url(r'^amendSite/(?P<id>\d+)$', amendSite, name='修改地址'),
    url(r'^deleteAlter/$', deleteAlter, name='删除'),
    url(r'^Alter/$', Alter, name='修改'),
    url(r'^submit/$', submit, name='确认'),
    url(r'^seve/$', seve, name='保存'),
    url(r'^notarize/$', notarize, name='提交'),
    url(r'^orderForm/$', orderForm, name='订单中心'),
    url(r'^pay/$', pay, name='支付'),
    url(r'^pay_all/$', pay_all, name='支付结束'),
]

apps/shoppingTrolley/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from shoppingTrolley.views import shopping, shopper, showshopp

urlpatterns = [
    url(r'^shop/$', shopping, name='购物'),
    url(r'^shopper/$', shopper, name='购物车'),
    url(r'showshopp/$', showshopp, name='商品页add'),
]

apps/user/urls.py
from django.conf.urls import url
from user.views import forget_password, reg, login, member, infor, message, delete

urlpatterns = [
    url(r'^login/$', login, name='登录'),
    url(r'^pass/$', forget_password, name='修改'),
    url(r'^reg/$', reg, name='注册'),
    url(r'^member/$', member, name='个人中心'),
    url(r'^infor/$', infor, name='个人信息'),
    url(r'^message/$', message, name='发送短信'),
    url(r'^delete/$', delete, name='退出'),
]

templates/personal/forgetpassword.html
{% extends 'father/index.html' %}
{% load static %}
{% block h_title %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>修改密码</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <link href="{% static 'css/amazeui.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
{% endblock %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">忘记密码</a>
        </h1>
    </header>
{% endblock %}

{% block content %}
    <div style="height: 80px;"></div>
    <form action="{% url 'user:修改' %}" method="post">
        {% csrf_token %}
        {% if data %}
            <input type="text" name="account" placeholder="{{ errors.account.0 }}" class="login-name">
            <input type="password" name="password1" placeholder="{{ errors.password1.0 }}" class="login-password">
            <input type="password" name="password2" placeholder="{{ errors.password2.0 }}" class="login-name">
        {% else %}
            <input type="text" name="account" placeholder="请输入手机号" class="login-name">
            <input type="password" name="password1" placeholder="请输入密码" class="login-password">
            <input type="password" name="password2" placeholder="确认密码" class="login-name">
        {% endif %}
        <input type="submit" class="login-btn" value="确认修改">
    </form>
{% endblock %}

templates/personal/infor.html
{% extends 'father/index.html' %}
{% load static %}
{% block h_css %}
    <link href="{% static 'css/check.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">个人资料</a>
        </h1>
    </header>
{% endblock %}

{% block content %}
    <div style="height: 49px;"></div>
    {#    {% if data %}#}
    <form action="{% url 'user:个人信息' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <ul class="safty1">
            <li>
                <a href="">
                    <i style="margin-top: 25px;">头像</i>
                    <div class="infor-pic">
                        <img src="{{ data.head.url }}"/>
                    </div>
                    <input type="file" name="head" value="上传头像">
                    {#                    <button type="file" class="am-btn am-btn-secondary am-round am-btn-xs" id="min" value="head">确认头像</button>#}
                </a>
            </li>
            <li>
                <i>昵称</i>
                <input type="text" class="infor-tele" name="nickname" {% if data.nickname %}
                       value="{{ data.nickname }}"
                {% else %}
                       placeholder="昵称"
                {% endif %} />
            </li>
            <li>
                <i>性别</i>
                <i class="infor-tele">
                    {% if data.sex == 1 %}
                        <label class="am-radio-inline">
                            <input type="radio" name="sex" checked="checked" value="1" data-am-ucheck>男
                        </label>
                        <label class="am-radio-inline">
                            <input type="radio" name="sex" value="2" data-am-ucheck>女
                        </label>
                    {% else %}
                        <label class="am-radio-inline">
                            <input type="radio" name="sex" value="1" data-am-ucheck>男
                        </label>
                        <label class="am-radio-inline">
                            <input type="radio" name="sex" checked="checked" value="2" data-am-ucheck>女
                        </label>
                    {% endif %}
                </i>
            </li>
            <li>
                <i>生日</i>
                <input type="date" class="infor-tele" name="birthday" value="{{ data.birthday|date:'Y-m-d' }}"
                       placeholder="出生日期"/>
            </li>
        </ul>
        <div style="height: 10px; background: #efefef;"></div>
        <ul class="safty1">
            <li>
                <i>学校</i>
                <input type="text" class="infor-tele" name="school"
                        {% if data.school %}
                       value="{{ data.school }}"
                        {% else %}
                       placeholder="就读于哪个学校"
                        {% endif %} />
            </li>
            <li>
                <i>位置</i>
                <input type="text" class="infor-tele" name="location"
                        {% if data.location %}
                       value="{{ data.location }}"
                        {% else %}
                       placeholder="详细地址"
                        {% endif %} />
            </li>
            <li>
                <i>故乡</i>
                <input type="text" class="infor-tele" name="nativePlace"
                        {% if data.nickname %}
                       value="{{ data.nativePlace }}"
                        {% else %}
                       placeholder="老家"
                        {% endif %}
                />
            </li>
            <li>
                <i>手机</i>
                <input type="text" class="infor-tele" name="telephone"
                        {% if data.telephone %}
                       value="{{ data.telephone }}"
                        {% else %}
                       placeholder="联系电话"
                        {% endif %}
                />
            </li>
        </ul>
        <input type="submit" class="login-btn" value="确认提交">
        <a href="{% url 'user:个人中心' %}"><input type="button" class="login-btn" value="返回个人中心"></a>
    </form>
{% endblock %}

templates/personal/login.html
{% extends 'father/index.html' %}
{% load static %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">登录</a>
        </h1>
    </header>
{% endblock %}
{% block content %}
    <div style="height: 49px;"></div>
    <div style="height: 3rem;"></div>
    <form action="{% url 'user:登录' %}" method="post">
        {% csrf_token %}
        {% if data %}
            <input type="text" name="account" id="mobile" placeholder="{{ errors.account.0 }}" class="login-name">
            <input type="password" name="password" id="password" placeholder="请输入密码" class="login-password">
        {% elif errors %}
            <input type="text" name="account" id="mobile" placeholder="请输入用户名/手机号" class="login-name">
            <input type="password" name="password" id="password" placeholder="{{ errors }}" class="login-password">
        {% else %}
            <input type="text" name="account" id="mobile" placeholder="请输入用户名/手机号" class="login-name">
            <input type="password" name="password" id="password" placeholder="请输入密码" class="login-password">
        {% endif %}
        <input type="submit" class="login-btn" value="我要登录">
    </form>
    <div class="agree">
        <a href="{% url 'user:注册' %}">免费注册</a>
        <a href="{% url 'user:修改' %}" class="forget">忘记密码？</a>
    </div>

{% endblock %}

{% block footer %}
    <div class="line"></div>
    <div class="line-text">第三方账号登录</div>
    <ul class="second-login">
        <li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/qqlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/sinalog.png' %}"/></a></li>
    </ul>
{% endblock %}

templates/personal/member.html
{% extends 'father/index.html' %}
{% load static %}
{% block header %}

{% endblock %}


{% block content %}
    <body style="background: #f6f6f6;">
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <h1 class="am-header-title">
            <a href="" class="">个人中心</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
    <div class="member">
        <div class="mem-tit">{{ user_nickname }}
            <a href="javascript:" class="step"><img src="{% static 'images/step.png' %}" width="26"/></a>
        </div>
        <div class="mem-pic">
            <div class="mem-pic-bg" style="background-image: url({{ MEDIA_URL }}{{ user_head }});"></div>
        </div>
        <ul class="member-menu">
            <li>
                <a href="javascript:">
                    <p class="yellow">0</p>
                    <p class="black">帐户余额 </p>
                </a>
            </li>
            <li>
                <a href="javascript:">
                    <p class="yellow">0</p>
                    <p class="black">积分 </p>
                </a>
            </li>
            <li>
                <a href="javascript:">
                    <p class="yellow">0</p>
                    <p class="black">优惠劵 </p>
                </a>
            </li>
            <li>
                <a href="javascript:">
                    <p class="yellow">0</p>
                    <p class="black">我的收藏 </p>
                </a>
            </li>
        </ul>
    </div>
    <div class="user-list">
        <div class="u-list-main">
            <img src="{% static 'images/order-pic.png' %}" width="27"/>
            <span>我的购物订单</span>
            <a href="javascript:">查看全部订单></a>
        </div>
        <ul class="user-nav">
            <li><a href="javascript:"> <img src="{% static 'images/1-icon.png' %}">
                <p>待付款</p></a></li>
            <li><a href="javascript:"> <img src="{% static 'images/1-icon1.png' %}">
                <p>待收货</p></a></li>
            <li><a href="javascript:"> <img src="{% static 'images/1-icon2.png' %}">
                <p>待评价</p></a></li>
            <li><a href="javascript:"> <img src="{% static 'images/1-icon3.png' %}">
                <p>退换货</p></a></li>
        </ul>
        <div class="u-list-main">
            <img src="{% static 'images/order-my.png' %}" width="27"/>
            <span>帐户与安全</span>
        </div>
        <ul class="user-nav">
            <li><a href="{% url 'user:个人信息' %}"> <img src="{% static 'images/1-icon4.png' %}">
                <p>个人资料</p></a></li>
            <li><a href="{% url 'add:地址' %}"> <img src="{% static 'images/1-icon5.png' %}">
                <p>收货地址</p></a></li>
            <li><a href="javascript:"> <img src="{% static 'images/1-icon6.png' %}">
                <p>安全设置</p></a></li>
            <li><a href="javascript:"> <img src="{% static 'images/1-icon7.png' %}">
                <p>我的钱包</p></a></li>
        </ul>
    </div>
    <!--导航-->
    <ul class="sq-nav"
        style=" background: #fff; margin-top: 1rem; border-top: 1px solid #ddd;  border-bottom: 1px solid #ddd;">
        <li>
            <div class="am-gallery-item">
                <a href="javascript:" class="">
                    <img src="{% static 'images/m_03.png' %}"/>
                    <p>我要兼职</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:" class="">
                    <img src="{% static 'images/m_04.png' %}"/>
                    <p>推荐有奖</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:" class="">
                    <img src="{% static 'images/m_05.png' %}"/>
                    <p>我的推荐</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/m_06.png' %}"/>
                    <p>我的佣金</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:" class="">
                    <img src="{% static 'images/m_02.png' %}"/>
                    <p>我的红包</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:" class="">
                    <img src="{% static 'images/m_07.png' %}"/>
                    <p>我的动态</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:;" class="index-qd">
                    <img src="{% static 'images/m_08.png' %}"/>
                    <p>客服中心</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'user:退出' %}" class="">
                    <img src="{% static 'images/m_09.png' %}"/>
                    <p>安全退出</p>
                </a>
            </div>
        </li>
    </ul>
    <!--客服中心-->
    <div class="qd-box">
        <div class="popup-title">
            <span>客服中心</span>
            <div class="popup-close"><i class="iconfont">&#xe602</i></div>
        </div>
        <div class="dq-text">
            <a href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes">
                <img src="{% static 'images/contactqq.png' %}" width="50"/>
                <p class="contactqq">联系QQ</p>
            </a>
            <a href="tel:0791-12345678">
                <img src="{% static 'images/contacttele.png' %}" width="50"/>
                <p class="contacttele">呼叫电话</p>
            </a>
        </div>
    </div>
{% endblock %}


{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'com:首页' %}" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="javascript:" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'shop:购物车' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="{% url 'add:订单中心' %}" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:个人中心' %}" class="curr">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}

templates/personal/reg.html
{% extends 'father/index.html' %}
{% load static %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">注册账户</a>
        </h1>
    </header>
{% endblock %}

{% block content %}
    <div style="height: 49px;"></div>
    <div style="height: 3rem;"></div>
    <form action="{% url 'user:注册' %}" method="post">
        {% csrf_token %}
        {% if data %}
            <input type="text" name="account" placeholder="{{ errors.account.0 }}" class="login-name">
            <input type="password" name="password1" placeholder="{{ errors.password1.0 }}" class="login-password">
            <input type="password" name="password2" placeholder="{{ errors.password2.0 }}" class="login-name">
            <div class="yzm" style="margin-top: 1.5rem;">
                <input type="text" class="reg-yzm" placeholder="输入验证码"/>
                <input type="button" class="yzm-hq" value="获取验证码"/>
            </div>
        {% else %}
            <input type="text" name="account" placeholder="请输入手机号" class="login-name">
            <input type="password" name="password1" placeholder="请输入密码" class="login-password">
            <input type="password" name="password2" placeholder="确认密码" class="login-name">
            <div class="yzm" style="margin-top: 1.5rem;">
                <input type="text" class="reg-yzm" placeholder="输入验证码"/>
                <input type="button" class="yzm-hq" value="获取验证码"/>
            </div>
        {% endif %}
        <input type="submit" class="login-btn" value="立即注册">
    </form>
    <div class="agree">
        <input type="checkbox" name="checkbox" value="同意" checked="">&nbsp;同意
        <a href="" class="xy">《用户协议》</a>
        <div class="r-login">已有账号，请<a href="{% url 'user:登录' %}" class="l-login">登录</a></div>
    </div>
{% endblock %}

{% block food_jss %}
    <script>
        $(function () {
            // 绑定到网页加载完毕事件里面
            $(".yzm-hq").on('click', function () {
                {#console.debug(111)#}
                var account = $("input[name='account']").val();
                var length = /^1[3-9]\d{9}/;
                if (!length.test(account)) {
                    alert("手机号码格式错误");
                    return;
                }
                var thit = this;
                // 发送ajax到后台进行验证
                $.ajax({
                    type: "post",
                    url: "{% url 'user:发送短信' %}",
                    data: {"account": account, "csrfmiddlewaretoken": "{{ csrf_token }}"},
                    dataType: "json",
                    success: function (data) {
                        if (data.errr == 0) {
                            //发送成功,开始倒计时
                            //初始化时间,与背景颜色,不能再次点击
                            var count = 5;
                            $(thit).css("background-color", 'gray');
                            $(thit).attr('disabled', "disabled");
                            var time = window.setInterval(function () {
                                //循环执行
                                --count;
                                var hint = count + "秒后点进重新获取";
                                $(thit).val(hint);
                                //结束判断
                                if (count == 0) {
                                    //还原颜色,可点击,原来展示内容,清除时间
                                    $(thit).css("background-color", '#76bb2a');
                                    $(thit).removeAttr("disabled");
                                    $(thit).val("获取验证码");
                                    window.clearInterval(time)
                                }
                            }, 1000)//时间计算速度
                        }
                    }
                })

            })
        })
    </script>
{% endblock %}