Superarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.decorators.cache import cache_page
from django.views.generic import RedirectView

from commodity.views import show

urlpatterns = [
    url(r'^$', cache_page(3600)(show)),  # 缓存到redis中首页
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('haystack.urls')),  # 全文搜索框架
    url(r'ckeditor', include("ckeditor_uploader.urls")),  # 用户上传的富文本域
    url(r'^user/', include('user.urls', namespace='user')),   # 用户模块
    url(r'^com/', include('commodity.urls', namespace='com')),   # 商品模块
    url(r'^car/', include('shoppingTrolley.urls', namespace='shop')),  # 购物车模块
    url(r'^add/', include('orderForm.urls', namespace='add')),  # 订单模块
    url(r'^favicon.ico$', RedirectView.as_view(url=r'static/favicon.ico'))
]

apps/commodity/urls.py
from django.conf.urls import url, include

from commodity.views import show, category, detail

urlpatterns = [
    url(r'^show/$', show, name='首页'),
    url(r'^category/(?P<id>\d+)/(?P<order>\d+)/$', category, name='商店'),
    url(r'^detail/(?P<id>\d+)/$', detail, name='详情'),
]

apps/orderForm/urls.py
from django.conf.urls import url
from orderForm.views import address, gladd, amendSite, deleteAlter, Alter, submit, notarize, orderForm, seve, pay, \
    pay_all

urlpatterns = [
    url(r'^address/$', address, name='添加地址'),
    url(r'^gladd/$', gladd, name='地址'),
    url(r'^amendSite/(?P<id>\d+)$', amendSite, name='修改地址'),
    url(r'^deleteAlter/$', deleteAlter, name='删除'),
    url(r'^Alter/$', Alter, name='修改'),
    url(r'^submit/$', submit, name='确认'),
    url(r'^seve/$', seve, name='保存'),
    url(r'^notarize/$', notarize, name='提交'),
    url(r'^orderForm/$', orderForm, name='订单中心'),
    url(r'^pay/$', pay, name='支付'),
    url(r'^pay_all/$', pay_all, name='支付结束'),
]

apps/shoppingTrolley/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from shoppingTrolley.views import shopping, shopper, showshopp

urlpatterns = [
    url(r'^shop/$', shopping, name='购物'),
    url(r'^shopper/$', shopper, name='购物车'),
    url(r'showshopp/$', showshopp, name='商品页add'),
]

apps/user/urls.py
from django.conf.urls import url
from user.views import forget_password, reg, login, member, infor, message, delete

urlpatterns = [
    url(r'^login/$', login, name='登录'),
    url(r'^pass/$', forget_password, name='修改'),
    url(r'^reg/$', reg, name='注册'),
    url(r'^member/$', member, name='个人中心'),
    url(r'^infor/$', infor, name='个人信息'),
    url(r'^message/$', message, name='发送短信'),
    url(r'^delete/$', delete, name='退出'),
]

templates/show/category.html
{% extends 'father/index.html' %}
{% load static %}
{% block h_css %}
    <style>
        .shop-list-mid .tit a {
            color: #909090;
            font-size: 1.4rem;
            display: -webkit-box;
            -webkit-box-orient: vertical;
            overflow: hidden;
            white-space: normal;
            text-overflow: ellipsis;
        }

        .list-price {
            background: url({% if order == 2 %}{% static 'images/order-bot.png' %}
            {% elif order == 3 %}{% static 'images/order-top.png' %}
            {% else %}{% static 'images/order.png' %}
            {% endif %}) no-repeat right center;
            padding-right: 20px;
            font-style: normal;
        }
    </style>
{% endblock %}

{% block content %}

    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <div class="cate-search">
            <form action="/search/" method="get">
                <input type="text" name="q" value="" class="cate-input" placeholder="请输入您要的搜索的产品关键词"/>
                <input type="submit" class="cate-btn" value=""/>
            </form>
        </div>
    </header>
    <div style="height: 49px;"></div>
    <ul class="list-nav">
        <li {% if order == 0 %}class="current"{% endif %}>
            <a href="{% url 'com:商店' id 0 %}">综合</a>
        </li>
        <li {% if order == 1 %}class="current"{% endif %}>
            <a href="{% url 'com:商店' id 1 %}">销量</a>
        </li>
        <li {% if order == 2 %}class="current"{% endif %}>
            <a href="{% url 'com:商店' id 2 %}"><i class="list-price">价格</i></a>
        </li>
        <li {% if order == 4 %}class="current"{% endif %}>
            <a href="{% url 'com:商店' id 4 %}">新品</a>
        </li>
    </ul>
    <div class="content-list">
        <div class="list-left">
            {% for cla in clas %}
                <li {% if id == cla.pk %}class="current"{% endif %}>
                    <a href="{% url 'com:商店' cla.pk order %}">{{ cla.class_name }}</a>
                </li>
            {% endfor %}
        </div>
        <div class="list-right">
            <ul class="list-pro">
                {% for good in Good %}
                    <li>
                        <a href="{% url 'com:详情' good.pk %}">
                            <img src="{{ MEDIA_URL }}{{ good.Goods_sku_Logo }}" class="list-pic"/>
                        </a>
                        <div class="shop-list-mid" style="width: 65%;">
                            <div class="tit"><a href="{% url 'com:详情' good.pk %}">{{ good.Goods_sku_name }}</a></div>
                            <div class="am-gallery-desc">￥{{ good.Goods_sku_Price }}</div>
                            <p>销量：{{ good.Goods_sku_Sellnum }}</p>
                        </div>
                        <div class="list-cart">
                            <div class="d-stock ">
                                <a class="decrease">-</a>
                                <input id="num" readonly="" class="text_box" name="" type="text" value="0"/>
                                <span style="display:none" class="id">{{ good.pk }}</span>
                                <a class="increase">+</a>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            {% if Good.has_previous %}
                <a href="?pig={{ Good.previous_page_number }}" class="am-btn">上一页</a>
            {% endif %}
            {% if Good.has_next %}
                <a href="?pig={{ Good.next_page_number }}" class="am-btn">下一页</a>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div class="fix-bot">
        <a href="{% url 'shop:购物车' %}">
            <div class="fix-bot-cart">
                <i id="all_num"></i>
            </div>
        </a>
        <a href="{% url 'add:提交' %}" class="list-js">去结算</a>
        <a href="#" class="list-jsk">一键快购</a>
    </div>
    {% csrf_token %}
{% endblock %}

{% block food_jss %}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                current_num += 1;
                if (current_num > 0) {
                    self.siblings(".decrease").fadeIn();
                    self.siblings(".text_box").fadeIn();
                }
                //设置数量
                var number = 1;
                //获取sku id;
                var sku_id = parseInt(self.siblings('span').html());
                //console.debug(sku_id);
                var v2 = $("input[name='csrfmiddlewaretoken']").val();
                $.ajax({
                    type: 'post',
                    url: "{% url 'shop:商品页add' %}",
                    data: {"sku_id": sku_id, 'number': number, "csrfmiddlewaretoken": v2},
                    dataType: "json",
                    success: function (data) {
                        if (data.age == 0) {
                            var over = confirm("尚未登录,是否跳转登录页面");
                            if (over) {
                                location.href = "{% url 'user:登录' %}";  // ?next= url 'com:商店' id sku.pk
                            }
                        } else if (data.age == 1) {
                            console.debug(data.all_num);
                            $("#all_num").text(data.all_num);
                        }
                    }
                });
                self.siblings('input').val(current_num);
            })
        });

        $('.decrease').click(function () {
            var self = $(this);
            var current_num = parseInt(self.siblings('input').val());
            //设置数量
            var number = -1;
            //获取sku id;
            var sku_id = parseInt(self.siblings('span').html());
            //console.debug(sku_id);
            var v2 = $("input[name='csrfmiddlewaretoken']").val();
            $.ajax({
                type: 'post',
                url: "{% url 'shop:商品页add' %}",
                data: {"sku_id": sku_id, 'number': number, "csrfmiddlewaretoken": v2},
                dataType: "json",
                success: function (data) {
                    if (data.age == 0) {
                        var over = confirm("尚未登录,是否跳转登录页面");
                        if (over) {
                            location.href = "{% url 'user:登录' %}";  // ?next= url 'com:商店' id sku.pk
                        }
                    } else if (data.age == 1) {
                        console.debug(data.all_num);
                        $("#all_num").text(data.all_num);
                    }
                }
            });
            if (current_num > 0) {
                current_num -= 1;
                if (current_num < 1) {
                    self.fadeOut();
                    self.siblings(".text_box").fadeOut();
                }
                self.siblings('input').val(current_num);
            }
        });
        $(function () {
            if ("{{ order }}" == 2) {
                $(".list-price").parent("a").attr('href', "{% url 'com:商店' id 3%}");
            } else if ("{{ order }}" == 3) {
                $(".list-price").parent("a").attr('href', "{% url 'com:商店' id 2 %}");
            }
        })
    </script>
{% endblock %}

templates/show/detail.html
{% extends 'father/index.html' %}
{% load static %}
{% block h_css %}
    <style>
        .am-slider-default .am-control-nav {
            text-align: center;
        }

        .am-slider-default .am-control-nav li a.am-active {
            background: #cb2527;
        }

        .am-slider-default .am-control-nav li a {
            border: 0;
            width: 10px;
            height: 10px;
        }
    </style>
{% endblock %}
{% block h_js %}
    <script>
        function changeImage() {
            document.getElementById("imgflag").src = "images/redherat.png";
        }
    </script>
{% endblock %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">商品详情</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <!--图片轮换-->
    <div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
        <ul class="am-slides">
            {% for s in sku.photoalbum_set.all %}
                <li><img src="{{ MEDIA_URL }}{{ s.Goods_Img_url }}"/></li>
            {% endfor %}
        </ul>
    </div>
    <div class="detal-info" style="position: relative; width: 100%;">
        <p>{{ sku.Goods_spu_id.Goods_spu_name }}&emsp;{{ sku.Goods_sku_name }}</p>
        <h2>商城价：
            <span>￥
                <span id="price">{{ sku.Goods_sku_Price }}</span>
                /{{ sku.Goods_sku_Unitinfo.class_unit }}
            </span>
        </h2>
        <div class="heart">
            <img src="{% static 'images/herat.png' %}" width="25" id="imgflag" onclick="changeImage()"/>
            <p>收藏</p>
        </div>
    </div>
    <div class="d-amount">
        <h4>数量：</h4>
        <div class="d-stock">
            <a class="decrease">-</a>
            <input id="num" readonly="" class="text_box" name="" type="text" value="1"/>
            <input id="id" type="hidden" value="644">
            <a class="increase">+</a>
            <span id="dprice" class="price" style="display:none"> 36</span>
        </div>
    </div>
    <div class="d-amount" style="position: relative; width: 100%;">
        <span>总价:&emsp;<span id="sum" style="font-size: 1.25em; color: #cb2527"></span>&emsp;元</span>
    </div>
    <div style="background: #eee; height: 10px;"></div>
    <div class="am-tabs detail-list" data-am-tabs>
        <ul class="am-tabs-nav am-nav am-nav-tabs">
            <li class="am-active"><a href="#tab1">商品详情</a></li>
            <li><a href="#tab2">商品评论</a></li>
        </ul>

        <div class="am-tabs-bd">
            <div class="am-tab-panel am-fade am-in am-active detail " id="tab1">
                <p>{{ sku.Goods_sku_intro|safe }}</p>
                <img src="{{ sku.Goods_sku_Logo.url }}"/>
            </div>
            <div class="am-tab-panel am-fade detail " id="tab2">
                <ul class="comment-list">
                    <li class="current"><a href="">全部</a></li>
                    <li><a href="">好评（20）</a></li>
                    <li><a href="">中评（5）</a></li>
                    <li><a href="">差评（0）</a></li>
                </ul>
                <ul class="comment-pic">
                    <li>
                        <div class="tit">
                            <img src="{% static 'images/tx.png' %}" class="tx"/>
                            <span>songke2014</span>
                            <i> [2016-01-01]</i>
                        </div>
                        <div class="comment-con">
                            买了些给家人，都说不错！
                        </div>
                    </li>
                    <li>
                        <div class="tit">
                            <img src="{% static 'images/tx.png' %}" class="tx"/>
                            <span>songke2014</span>
                            <i> [2016-01-01]</i>
                        </div>
                        <div class="comment-con">
                            买了些给家人，都说不错！
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    {% csrf_token %}
    <input type="hidden" name="sku_id" value="{{ sku.pk }}">
{% endblock %}


{% block footer %}
    <!--底部-->
    <div style=" height: 55px;"></div>
    <ul class="fix-shopping">
        <li><a href="javascript:" class="join">加入购物车</a></li>
        <li><a href="#" class="imm-buy">立即购买</a></li>
    </ul>
{% endblock %}


{% block food_jss %}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                current_num += 1;
                self.siblings('input').val(current_num);
            });
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 1) {
                    current_num -= 1;
                    self.siblings('input').val(current_num);
                }
            })
        });
        $(function () {
            $('.join').on('click', function () {
                {# 获取数量#}
                var number = $("#id").val();
                var v2 = $("input[name='csrfmiddlewaretoken']").val();
                console.debug(number);
                $.ajax({
                    type: 'post',
                    url: "{% url 'shop:购物' %}",
                    data: {'sku_id': {{ sku.pk }}, 'number': number, "csrfmiddlewaretoken": v2},
                    dataType: "json",
                    success: function (data) {
                        if (data.age == 0) {
                            var over = confirm("尚未登录,是否跳转登录页面");
                            if (over) {
                                location.href = "{% url 'user:登录' %}?next={% url 'com:详情' sku.pk %}"
                            }
                        } else if (data.age == 1) {
                            confirm("商品数量尚未选择")
                        } else if (data.age == 2) {
                            var com = confirm("参数错误");
                            if (com) {
                                location.href("{% url 'com:商店' 1 0 %}")
                            }
                        } else if (data.age == 3) {
                            alert("添加购物车和成功");
                        }
                    }
                })
            })
        });
    </script>
{% endblock %}

templates/show/index.html
{% extends 'father/index.html' %}
{% load static %}

{% block content %}
    <div style="height: 49px;"></div>
    <!--图片轮换-->
    <div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
        <ul class="am-slides">
            {% for one in data %}
                <li><a href="{{ one.Goods_sku_id }}"><img src="{{ one.Page_Imgurl.url }}"/></a></li>
            {% endfor %}
        </ul>
    </div>
    <!--导航-->
    <ul class="sq-nav">
        <li>
            <div class="am-gallery-item">
                <a href="recharge.html" class="">
                    <img src="{% static 'images/icon.png' %}"/>
                    <p>充值</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:;" class="index-qd">
                    <img src="{% static 'images/icon1.png' %}"/>
                    <p>签到</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="yhq.html" class="">
                    <img src="{% static 'images/icon2.png' %}"/>
                    <p>红包</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/icon3.png' %}"/>
                    <p>即将上线</p>
                </a>
            </div>
        </li>
    </ul>
    <ul class="sq-nav1">
        <li>
            <div class="am-gallery-item">
                <a href="speed.html" class="">
                    <img src="{% static 'images/icon4.png' %}"/>
                    <p>零食飞速</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'com:商店' 1 0 %}" class="">
                    <img src="{% static 'images/icon5.png' %}"/>
                    <p>超市</p>
                </a>
            </div>
        </li>

    </ul>
    <div class="h-line"></div>
    <!--不规则展示-->
    <div class="index-product">
        <div class="index-pro-lf"><a href="{{ home.0.Home_Linkurl }}"><img src="{{ home.0.Home_Imgurl.url }}"/></a>
        </div>
        <div class="index-pro-lr"><a href="{{ home.1.Home_Linkurl }}"><img src="{{ home.1.Home_Imgurl.url }}"/></a>
        </div>
    </div>
    <div class="product-bot">
        <div class="product-bot-lf"><a href="{{ home.2.Home_Linkurl }}"><img src="{{ home.2.Home_Imgurl.url }}"/></a>
        </div>
        <div class="product-bot-lr">
            <div class="top"><a href="{{ home.3.Home_Linkurl }}"><img src="{{ home.3.Home_Imgurl.url }}"/></a></div>
            <div class="bot">
                <div class="bot-lf"><a href="{{ home.4.Home_Linkurl }}"><img src="{{ home.4.Home_Imgurl.url }}"/></a>
                </div>
                <div class="bot-lr"><a href="{{ home.5.Home_Linkurl }}"><img src="{{ home.5.Home_Imgurl.url }}"/></a>
                </div>
            </div>
        </div>
    </div>
    <!--不规则展示-->
    <div class="h-line"></div>
    <!-- 特色专区-->


    {% for act in activ %}
        <div class="sq-title">
            <img src="{% static 'images/ts.png' %}" width="26"/>
            {{ act.Activity }}
        </div>

        <ul data-am-widget="gallery"
            class="am-gallery pro-list am-avg-sm-2 am-avg-md-2 am-avg-lg-4 am-gallery-default">
            {% for a in act.division_set.all %}
                <li>
                    <div class="am-gallery-item">
                        <a href="{% url 'com:详情' a.Division_sku_id %}" class="">
                            <img src="{{ a.Division_sku.Goods_sku_Logo.url }}"/>
                            <h3 class="am-gallery-title">
                                {{ a.Division_sku.Goods_spu_id.Goods_spu_name }}{{ a.Division_sku.Goods_sku_name }}</h3>
                            <div class="am-gallery-desc">
                                ￥{{ a.Division_sku.Goods_sku_Price }}/{{ a.Division_sku.Goods_sku_Unitinfo }}</div>
                        </a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% endfor %}
    <!--签到-->
    <div class="qd-box">
        <div class="popup-title">
            <span>签到成功</span>
            <div class="popup-close"><i class="iconfont">&#xe602</i></div>
        </div>
        <div class="dq-text">
            <img src="{% static 'images/qiandao.png' %}" width="40"/>&nbsp; 您已连续签到3天
        </div>
    </div>
{% endblock %}


{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'com:首页' %}" class="curr">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="#" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'shop:购物车' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="{% url 'add:订单中心' %}" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:个人中心' %}" class="">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}