Superarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.decorators.cache import cache_page
from django.views.generic import RedirectView

from commodity.views import show

urlpatterns = [
    url(r'^$', cache_page(3600)(show)),  # 缓存到redis中首页
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('haystack.urls')),  # 全文搜索框架
    url(r'ckeditor', include("ckeditor_uploader.urls")),  # 用户上传的富文本域
    url(r'^user/', include('user.urls', namespace='user')),   # 用户模块
    url(r'^com/', include('commodity.urls', namespace='com')),   # 商品模块
    url(r'^car/', include('shoppingTrolley.urls', namespace='shop')),  # 购物车模块
    url(r'^add/', include('orderForm.urls', namespace='add')),  # 订单模块
    url(r'^favicon.ico$', RedirectView.as_view(url=r'static/favicon.ico'))
]

apps/commodity/urls.py
from django.conf.urls import url, include

from commodity.views import show, category, detail

urlpatterns = [
    url(r'^show/$', show, name='首页'),
    url(r'^category/(?P<id>\d+)/(?P<order>\d+)/$', category, name='商店'),
    url(r'^detail/(?P<id>\d+)/$', detail, name='详情'),
]

apps/orderForm/urls.py
from django.conf.urls import url
from orderForm.views import address, gladd, amendSite, deleteAlter, Alter, submit, notarize, orderForm, seve, pay, \
    pay_all

urlpatterns = [
    url(r'^address/$', address, name='添加地址'),
    url(r'^gladd/$', gladd, name='地址'),
    url(r'^amendSite/(?P<id>\d+)$', amendSite, name='修改地址'),
    url(r'^deleteAlter/$', deleteAlter, name='删除'),
    url(r'^Alter/$', Alter, name='修改'),
    url(r'^submit/$', submit, name='确认'),
    url(r'^seve/$', seve, name='保存'),
    url(r'^notarize/$', notarize, name='提交'),
    url(r'^orderForm/$', orderForm, name='订单中心'),
    url(r'^pay/$', pay, name='支付'),
    url(r'^pay_all/$', pay_all, name='支付结束'),
]

apps/shoppingTrolley/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from shoppingTrolley.views import shopping, shopper, showshopp

urlpatterns = [
    url(r'^shop/$', shopping, name='购物'),
    url(r'^shopper/$', shopper, name='购物车'),
    url(r'showshopp/$', showshopp, name='商品页add'),
]

apps/user/urls.py
from django.conf.urls import url
from user.views import forget_password, reg, login, member, infor, message, delete

urlpatterns = [
    url(r'^login/$', login, name='登录'),
    url(r'^pass/$', forget_password, name='修改'),
    url(r'^reg/$', reg, name='注册'),
    url(r'^member/$', member, name='个人中心'),
    url(r'^infor/$', infor, name='个人信息'),
    url(r'^message/$', message, name='发送短信'),
    url(r'^delete/$', delete, name='退出'),
]

apps/orderForm/models.py
from django.db import models
from commodity.models import Goods
from db.base_model import BaseModel
from user.models import Username


class DeliveryAddress(BaseModel):
    # 收货地址
    """
    用户ID
    收货人姓名
    手机号码
    省ID
    市ID
    区ID
    街道ID
    详细描述
    是否是默认地址
    """
    # Is_default = (
    #     (1, '默认'),
    #     (0, '不默认'),
    # )
    user = models.ForeignKey(to=Username, verbose_name='用户id')
    userName = models.CharField(max_length=50, verbose_name='收货人姓名')
    telephone = models.CharField(max_length=11, verbose_name='电话号码')
    harea = models.CharField(max_length=50, null=True, blank=True, verbose_name='省')
    hproper = models.CharField(max_length=50, null=True, blank=True, verbose_name='市')
    hcity = models.CharField(max_length=50, verbose_name='区')
    street = models.CharField(max_length=50, verbose_name='街道')
    inDetail = models.CharField(max_length=255, verbose_name='详细描述')
    default = models.BooleanField(default=False, verbose_name="默认地址")

    def __str__(self):
        return self.userName

    class Meta:
        db_table = "DeliveryAddress"
        verbose_name = '收货地址'
        verbose_name_plural = verbose_name


class Payment(BaseModel):
    # 付款方式
    """
    付款名称
    结账图片
    """
    pay = models.CharField(max_length=50, verbose_name='付款名称')
    payImg = models.ImageField(upload_to='Home/%Y%m/%d', verbose_name='支付图片')

    class Meta:
        db_table = "payment"
        verbose_name = '付款方式'
        verbose_name_plural = verbose_name


class OrderInformation(BaseModel):
    # 订单信息
    """
    订单编号
    订单金额
    用户ID
    收货人姓名
    收货人电话
    收货id
    订单状态
    运输id
    付款id
    实付金额
    """
    State = {
        (0, '待付款'),
        (1, '退发货'),
        (2, '待收货'),
        (3, '待评价'),
        (4, '已完成'),
    }
    orderNum = models.CharField(max_length=50, verbose_name='订单编号', unique=True)
    orderPrice = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='订单价格')
    UserKey = models.ForeignKey(to=Username, verbose_name='用户ID')
    UserName = models.CharField(max_length=50, verbose_name='收货人姓名')
    Telephone = models.CharField(max_length=11, verbose_name='收货人电话')
    AddressKey = models.ForeignKey(to='DeliveryAddress', on_delete=models.CASCADE, verbose_name='收货地址')
    orderState = models.SmallIntegerField(choices=State, default=0, verbose_name='订单状态')
    transitKey = models.CharField(max_length=50, verbose_name='运输方式')
    transit_price_Key = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='运输价格')
    PaymentKey = models.ForeignKey(to="Payment", on_delete=models.CASCADE, null=True, blank=True, verbose_name='付款方式')
    money = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='实际支付')

    class Meta:
        db_table = "OrderInformation"
        verbose_name = '订单信息'
        verbose_name_plural = verbose_name


class OrdersGoods(BaseModel):
    # 订单商品
    """
    订单ID
    商品SKU ID
    商品数量
    商品价格
    """
    OrderInformation = models.ForeignKey(to="OrderInformation", on_delete=models.CASCADE, verbose_name='订单信息')
    goodsSku = models.ForeignKey(to=Goods, on_delete=models.CASCADE, verbose_name='SKU商品')
    goodsNum = models.SmallIntegerField(verbose_name='商品数量')
    goodsPrice = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='商品价格')

    class Meta:
        db_table = "OrdersGoods"
        verbose_name = '订单商品'
        verbose_name_plural = verbose_name


class TypeShipping(BaseModel):
    # 运输方式
    """
    ID
    名称
    价格
    """
    transit = models.CharField(max_length=50, verbose_name='运输名称')
    transitCharge = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='运输价格', default=0)

    class Meta:
        db_table = "TypeShipping"
        verbose_name = '运输方式'
        verbose_name_plural = verbose_name

apps/orderForm/views.py
from datetime import datetime
from alipay import AliPay
from django.db import transaction
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django_redis import get_redis_connection
import random
from Superarket import settings
from commodity.models import Goods
from orderForm.form import AddressAddForm, AlterAddForm
from orderForm.models import DeliveryAddress, TypeShipping, OrderInformation, OrdersGoods
from user.helper import old_request
import os
import time
from django.http import HttpResponse


# 添加地址
def address(request):
    """
    添加收货地址
    :param request:
    :return:
    """
    if request.method == 'POST':
        # 获取数据
        data = request.POST.dict()
        # 赋值id进行数量计算
        user_id = request.session.get("user_id")
        data['user_id'] = user_id
        # 处理数据,获得处理后的数据
        form = AddressAddForm(data)
        # 接收清理干净的数据
        if form.is_valid():
            cleaned_data = form.cleaned_data
            # 手动添加必要参数
            cleaned_data['user_id'] = request.session.get("user_id")
            # 保存到数据库
            DeliveryAddress.objects.create(**cleaned_data)
            # 跳转页面
            return redirect("add:地址")
        else:
            # 如果格式不对或未填写,则返回报错内容,接收
            context = {
                'form': form,
            }
            # 渲染到页面
            return render(request, "orderForm/address.html", context)
    else:
        return render(request, "orderForm/address.html")


# 展示区
def gladd(request):
    """
    收货地址展示页
    :param request:
    :return:
    """
    if request.method == 'GET':
        user_id = request.session.get("user_id")
        if request.session.get("user_id") is None:
            # 没有登录跳转页面
            return redirect("user:登录")
        else:
            all = DeliveryAddress.objects.filter(user_id=user_id).order_by("-default")
            context = {
                'all': all,
            }
            return render(request, "orderForm/gladdress.html", context)
    else:
        return redirect("user:个人中心")


# 修改地址
def amendSite(request, id):
    """
    修改地址
    :param request:
    :return:
    """
    if request.method == 'POST':
        data = request.POST.dict()
        # 赋值id进行数量计算
        user_id = request.session.get("user_id")
        data['user_id'] = user_id
        # 处理数据,获得处理后的数据
        form = AlterAddForm(data)
        # 接收清理干净的数据
        if form.is_valid():
            cleaned_data = form.cleaned_data
            # 手动添加必要参数
            # cleaned_data['user_id'] = request.session.get("user_id")
            # 保存到数据库
            DeliveryAddress.objects.filter(user_id=user_id, pk=id).update(**cleaned_data)
            # 跳转展示页面
            return redirect("add:地址")
        else:
            # 如果格式不对或未填写,则返回报错内容,接收
            context = {
                'form': form,
            }
            # 渲染到页面
            return render(request, "orderForm/addadd.html", context)
    else:
        user_id = request.session.get("user_id")
        if request.session.get("user_id") is None:
            # 没有登录跳转页面
            return redirect("user:登录")
        else:
            try:
                all = DeliveryAddress.objects.get(user_id=user_id, pk=id)
            except DeliveryAddress.DoesNotExist:
                return redirect("add:地址")
            context = {
                'all': all,
            }
            return render(request, "orderForm/addadd.html", context)


# 删除地址
def deleteAlter(request):
    if request.method == "POST":
        user_id = request.session.get("user_id")
        addId = request.POST.get('id')
        addId = int(addId)
        number = DeliveryAddress.objects.filter(user_id=user_id, pk=addId).delete()
        if number:
            return JsonResponse({'age': 0, 'clue': '删除成功'})
        else:
            return JsonResponse({'age': 1, 'clue': '删除失败'})
    else:
        if request.session.get("user_id") is None:
            # 没有登录跳转页面
            return redirect("user:登录")
        else:
            return redirect("add:地址")


# 更改默认地址
def Alter(request):
    if request.method == "POST":
        user_id = request.session.get("user_id")
        addId = request.POST.get('id')
        addId = int(addId)
        DeliveryAddress.objects.filter(user_id=user_id).update(default=False)
        number = DeliveryAddress.objects.filter(user_id=user_id, pk=addId).update(default=True)
        if number:
            return JsonResponse({'age': 2, 'clue': '修改成功'})
        else:
            return JsonResponse({'age': 3, 'clue': '修改失败'})
    else:
        if request.session.get("user_id") is None:
            # 没有登录跳转页面
            return redirect("user:登录")
        else:
            return redirect("add:地址")


# 先确认订单
@old_request
def submit(request):
    if request.method == "POST":
        return redirect('shop:购物车')
    else:
        # 获取登录用户的id
        user_id = request.session.get("user_id")
        # 获取地址
        Address = DeliveryAddress.objects.filter(is_delete=False).order_by('-default').first()
        # 获取商品id,建立radis链接
        user_id = "User_{}".format(user_id)
        cnn = get_redis_connection('default')
        sku_ids = request.GET.getlist("sku_id")
        # print(sku_ids)
        goods = []
        allprice = 0
        for sku_id in sku_ids:
            try:
                sku_id = int(sku_id)
            except:
                return redirect("shop:购物车")
            # 根据id 查询商品Goods
            good = Goods.objects.get(pk=sku_id, is_delete=False)
            goods.append(good)
            # 根据id,查询数量
            count = cnn.hget(user_id, sku_id)
            count = int(count)
            good.count = count
            # 商品总价格
            price = count * good.Goods_sku_Price
            allprice += price
        # print(goods)
        # 查询运输方式
        carriage = TypeShipping.objects.all().order_by('transitCharge')
        # 渲染到页面
        contxet = {
            'Address': Address,
            'Goods': goods,
            'carriage': carriage,
            'allprice': allprice,
        }
        return render(request, 'orderForm/tureorder.html', contxet)


# 存储确认后的订单信息
@transaction.atomic
def seve(request):
    if request.method == 'POST':
        user_id = request.session.get("user_id")
        # 接收传递过来的地址id, 商品id, 运输方式id
        address_id = request.POST.get("address")
        sku_ids = request.POST.getlist("sku_id")
        carriage_id = request.POST.get("carriage")

        # 判断地址id是否是整数
        try:
            address_id = int(address_id)
        except:
            return JsonResponse({"age": 1, "matter": '地址参数错误'})
        # 查询地址id是否存在
        try:
            address = DeliveryAddress.objects.get(pk=address_id)
        except DeliveryAddress.DoesNotExist:
            return JsonResponse({"age": 2, "matter": '地址不存在'})

        # 判断商品id是否是整数
        try:
            sku_intid = [int(sku_id) for sku_id in sku_ids]
        except:
            return JsonResponse({"age": 3, "matter": '商品参数错误'})

        # 判断商品是否存在
        for sku_id in sku_intid:
            try:
                Goods.objects.get(pk=sku_id)
            except Goods.DoesNotExist:
                return JsonResponse({"age": 4, "matter": '商品不存在'})

        # 判断运输方式id是否是整数
        try:
            carriage_id = int(carriage_id)
        except:
            return JsonResponse({"age": 5, "matter": '运输参数错误'})

        # 判断运输方式是否存在
        try:
            shopp = TypeShipping.objects.get(pk=carriage_id)
        except TypeShipping.DoesNotExist:
            return JsonResponse({"age": 6, "matter": '运输方式不存在'})

        # 保存数据到订单信息表内,先准备需要的字段的值
        #
        #     订单金额
        #     用户ID
        #     收货人姓名
        #     收货人电话
        #     收货地址id
        #     订单状态
        #     运输方式
        #     付款id
        #     实付金额

        # 订单编号:随机在A-Z中选取一个大写英文字母 大写字母,年月日,随机数
        try:
            number = "{}{}{}".format(datetime.now().strftime('%Y%m%d%H%M%S'), user_id, (random.randint(10000, 99999)))
        except:
            return JsonResponse({"age": 7, "matter": '生成订单号错误'})
        # 用户ID
        # print(orderNum)
        # UserKey = user_id
        # # 收货人姓名
        # UserName = address.userName
        # # 收货人电话
        # Telephone = address.telephone
        # # 收货地址id
        # AddressKey = address.pk
        # # 运输方式
        # transitKey = shopp.transit
        # # 运输价格
        # transit_price_Key = shopp.transitCharge
        # print(number)
        # print(UserKey)
        # print(UserName)
        # print(Telephone)
        # print(AddressKey)
        # print(transitKey)
        # print(transit_price_Key)

        # 生成事务
        sid = transaction.savepoint()
        # 保存数值
        try:
            information = OrderInformation.objects.create(
                orderNum=number,
                UserKey_id=user_id,
                UserName=address.userName,
                Telephone=address.telephone,
                AddressKey_id=address.pk,
                transitKey=shopp.transit,
                transit_price_Key=shopp.transitCharge,
            )
        except:
            # 回滚事务
            transaction.savepoint_rollback(sid)
            return JsonResponse({"age": 8, "matter": '保存订单信息出错'})

        # 链接radis
        try:
            # 建立连接
            cnn = get_redis_connection('default')
            # 准备key
            user_id = "User_{}".format(user_id)
        except:
            return JsonResponse({"age": 9, "matter": '建立radis错误'})
        # 准备总金额
        allprice = 0
        # 保存订单商品信息,查询数量
        for sku_id in sku_intid:
            try:
                goods = Goods.objects.get(pk=sku_id, is_delete=False, Goods_sku_Is_putaway=1)
            except Goods.DoesNotExist:
                return JsonResponse({"age": 10, "matter": '商品不存在'})

            # 获取购物车的数量
            try:
                count = cnn.hget(user_id, sku_id)
                count = int(count)
            except:
                return JsonResponse({"age": 11, "matter": '获取数量错误'})

            # 判断库存

templates/orderForm/order.html
{% extends 'father/index.html' %}
{% load static %}
{% block food_js %}
    <script type="text/javascript">
        $(function () {
            $('#beginTime').date();
            $('#endTime').date({theme: "datetime"});
        });
    </script>
{% endblock %}
{% block h_js %}

    <script src="{% static 'js/date.js' %}"></script>
    <script src="{% static 'js/iscroll.js' %}"></script>
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div style="height: 49px;"></div>
    <ul class="order-detail">
        <li><span>订单名称：</span>电子产品</li>
    </ul>
    <h5 class="order-tit">收货人信息</h5>
    <div class="order-name">
        <a href="javascript:">
            <p class="order-tele">{{ order.UserName }}&nbsp;&nbsp;&nbsp;{{ order.Telephone }}</p>
            <p class="order-add">
                {{ order.AddressKey.hcity }}{{ order.AddressKey.hproper }}{{ order.AddressKey.harea }}</p>
        </a>
    </div>
    <div style="background: #eee; height: 10px;"></div>
    <h5 class="order-tit">订单信息</h5>
    <ul class="shopcart-list" style="padding-bottom: 0; margin-top: 0;">
        {% for one in order.ordersgoods_set.all %}
            <li>
                <img src="{{ MEDIA_URL }}{{ one.goodsSku.Goods_sku_Logo }}" class="shop-pic"/>
                <div class="order-mid">
                    <div class="tit">
                        {{ one.goodsSku.Goods_spu_id.Goods_spu_name }}{{ one.goodsSku.Goods_sku_name }}</div>
                    <div class="order-price">
                        ￥{{ one.goodsPrice }}<i>X{{ one.goodsNum }}</i>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
    <ul class="order-infor">
        <li class="order-infor-first">
            <span>商品总计：</span>
            <i>￥{{ order.orderPrice }}</i>
        </li>
        <li class="order-infor-first">
            <span>运输方式：</span>
            <i>{{ order.transitKey }}</i>
        </li>
    </ul>
    <h5 class="order-tit">支付方式</h5>
    <ul class="pay-style">
        <li>
            <img src="{% static 'images/zhi.png' %}" width="50"/>
            <span>
                    <p>支付宝</p>
                    <p class="descript">推荐有支付宝账号的用户使用</p>
                </span>
            <label class="am-radio-inline">
                <input type="radio" checked="checked" name="radio10" value="1" data-am-ucheck>
            </label>
        </li>
        <li>
            <img src="{% static 'images/wei.png' %}" width="50"/>
            <span>
                <p>微信支付</p>
                <p class="descript">推荐安装微信5.0及以上版本的使用</p>
             </span>
            <label class="am-radio-inline">
                <input type="radio" name="radio10" value="1" data-am-ucheck>
            </label>
        </li>
    </ul>
    <div style="background: #eee; height: 10px;"></div>
    <textarea placeholder="备注说明" class="bz-infor"></textarea>
    <div style="background: #eee; height: 10px;"></div>
    <div style="height: 55px;"></div>
    <div class="shop-fix">
        <div class="order-text">
            应付总额：<span>￥{{ price }}</span>
        </div>
        <a href="{% url 'add:支付' %}?orderNum={{ order.orderNum }}" class="js-btn">确认支付</a>
    </div>
{% endblock %}


{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'com:首页' %}" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="javascript:" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'shop:购物车' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="{% url 'add:订单中心' %}" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:个人中心' %}" class="curr">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}

templates/orderForm/pay.html
{% extends 'father/index.html' %}
{% load static %}
{% block header %}
    <body style="background: #f0f0f0;">
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">完成支付</a>
        </h1>
    </header>
{% endblock %}
{% block content %}
    <div style="height: 49px;"></div>
    <ul class="order-detail">
        <li><span>支付结果：{{ error }}</span></li>
    </ul>
{% endblock %}

templates/orderForm/tureorder.html
{% extends 'father/index.html' %}
{% load static %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">确认订单</a>
        </h1>
    </header>
{% endblock %}

{% block content %}
    <div style="height: 49px;"></div>
    <form action="" id="form">
        <h5 class="order-tit">收货人信息</h5>
        <div class="order-name">
            {% if Address %}
                <input type="hidden" name="address" value="{{ Address.id }}">
                <a href="{% url 'add:地址' %}">
                    <p class="order-tele">
                        姓名:&nbsp;{{ Address.userName }}&nbsp;&nbsp;电话:&nbsp;{{ Address.telephone }}</p>
                    <p class="order-add">
                        {{ Address.hcity }}
                        {{ Address.hproper }}
                        {{ Address.harea }}
                        {{ Address.street }}
                    </p>
                </a>
                <i class="am-icon-angle-right"></i>
            {% else %}
                <a href="address.html">+新建收货地址</a>
                <i class="am-icon-angle-right"></i>
            {% endif %}
        </div>
        <div style="background: #eee; height: 10px;"></div>
        <h5 class="order-tit">确认订单信息</h5>
        <ul class="shopcart-list" style="padding-bottom: 0;">
            {% for Good in Goods %}
                <li>
                    <input type="hidden" name="sku_id" value="{{ Good.id }}">
                    <img src="{{ MEDIA_URL }}{{ Good.Goods_sku_Logo }}" class="shop-pic"/>
                    <div class="order-mid">
                        <div class="tit">{{ Good.Goods_spu_id.Goods_spu_name }}{{ Good.Goods_sku_name }}</div>
                        <div class="order-price">￥{{ Good.Goods_sku_Price }} <i>X{{ Good.count }}</i></div>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <div style="background: #eee; height: 10px;"></div>
        <ul class="order-infor">
            <li class="order-infor-first">
                <span>商品总计：</span>
                <i>￥<span id="allprice">{{ allprice }}</span></i>
            </li>
            <li class="order-infor-first">
                <span>运输方式：</span>
                <i>
                    <select name="carriage" id="Charge">
                        {% for carr in carriage %}
                            <option value="{{ carr.id }}"
                                    price="{{ carr.transitCharge }}">{{ carr.transit }}-￥{{ carr.transitCharge }}</option>
                        {% endfor %}
                    </select>
                </i>
            </li>
            <li class="order-infor-first">
                <a href="">积分抵费></a>
            </li>
            <li class="order-infor-first">
                <a href="">选择优惠券></a>
            </li>
        </ul>
        {% csrf_token %}
    </form>
    <div style="background: #eee; height: 10px;"></div>
    <textarea placeholder="备注说明" class="bz-infor"></textarea>
    <div style="background: #eee; height: 10px;"></div>
    <div style="height: 55px;"></div>
    <div class="shop-fix">
        <div class="order-text">
            应付总额：<span id="reality">￥188</span>
        </div>
        <a href="javascript:" class="js-btn" id="refer">提交订单</a>
    </div>
{% endblock %}


{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'com:首页' %}" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'shop:购物车' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="{% url 'add:订单中心' %}" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:个人中心' %}" class="curr">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}

{% block food_jss %}
    <script>
        $(function () {
            function transitCharge() {
                //获取商品总价格
                var allprice = $("#allprice").text();
                //获取选中下拉框的自定义属性的值
                var transitCharge = $("#Charge").find(":selected").attr('price');
                //计算实际支付价格
                var number = parseFloat(allprice) + parseFloat(transitCharge);
                $("#reality").text(number)
            }

            transitCharge();
            //当下拉框改变选中值的时候,价格跟着一起改变
            $('#Charge').on('change', function () {
                transitCharge()
            });

            //传送确认订单必须要的地址id, 商品id, 运输方式id
            $('#refer').on('click', function () {
                //获取form表单里面的值
                var data = $('#form').serialize();
                $.ajax({
                    type: 'POST',
                    url: '{% url 'add:保存' %}',
                    data: data,
                    dataType: 'json',
                    success: function (data) {
                        if (data.age == 0) {
                            location.href = "{% url 'add:提交' %}?orderNum=" + data.orderNum
                        } else {
                            alert("订单创建失败")
                        }
                    }
                })
            })
        });
    </script>
{% endblock %}