Superarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.decorators.cache import cache_page
from django.views.generic import RedirectView

from commodity.views import show

urlpatterns = [
    url(r'^$', cache_page(3600)(show)),  # 缓存到redis中首页
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('haystack.urls')),  # 全文搜索框架
    url(r'ckeditor', include("ckeditor_uploader.urls")),  # 用户上传的富文本域
    url(r'^user/', include('user.urls', namespace='user')),   # 用户模块
    url(r'^com/', include('commodity.urls', namespace='com')),   # 商品模块
    url(r'^car/', include('shoppingTrolley.urls', namespace='shop')),  # 购物车模块
    url(r'^add/', include('orderForm.urls', namespace='add')),  # 订单模块
    url(r'^favicon.ico$', RedirectView.as_view(url=r'static/favicon.ico'))
]

apps/commodity/urls.py
from django.conf.urls import url, include

from commodity.views import show, category, detail

urlpatterns = [
    url(r'^show/$', show, name='首页'),
    url(r'^category/(?P<id>\d+)/(?P<order>\d+)/$', category, name='商店'),
    url(r'^detail/(?P<id>\d+)/$', detail, name='详情'),
]

apps/orderForm/urls.py
from django.conf.urls import url
from orderForm.views import address, gladd, amendSite, deleteAlter, Alter, submit, notarize, orderForm, seve, pay, \
    pay_all

urlpatterns = [
    url(r'^address/$', address, name='添加地址'),
    url(r'^gladd/$', gladd, name='地址'),
    url(r'^amendSite/(?P<id>\d+)$', amendSite, name='修改地址'),
    url(r'^deleteAlter/$', deleteAlter, name='删除'),
    url(r'^Alter/$', Alter, name='修改'),
    url(r'^submit/$', submit, name='确认'),
    url(r'^seve/$', seve, name='保存'),
    url(r'^notarize/$', notarize, name='提交'),
    url(r'^orderForm/$', orderForm, name='订单中心'),
    url(r'^pay/$', pay, name='支付'),
    url(r'^pay_all/$', pay_all, name='支付结束'),
]

apps/shoppingTrolley/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from shoppingTrolley.views import shopping, shopper, showshopp

urlpatterns = [
    url(r'^shop/$', shopping, name='购物'),
    url(r'^shopper/$', shopper, name='购物车'),
    url(r'showshopp/$', showshopp, name='商品页add'),
]

apps/user/urls.py
from django.conf.urls import url
from user.views import forget_password, reg, login, member, infor, message, delete

urlpatterns = [
    url(r'^login/$', login, name='登录'),
    url(r'^pass/$', forget_password, name='修改'),
    url(r'^reg/$', reg, name='注册'),
    url(r'^member/$', member, name='个人中心'),
    url(r'^infor/$', infor, name='个人信息'),
    url(r'^message/$', message, name='发送短信'),
    url(r'^delete/$', delete, name='退出'),
]

apps/shoppingTrolley/models.py
from django.db import models

# Create your models here.

apps/shoppingTrolley/views.py
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse, redirect
from django_redis import get_redis_connection

from commodity.models import Goods
from user.helper import old_request

"""
# 类型转换
def to_int(str):
    try:
        int(str)
        return int(str)
    except ValueError:  # 报类型错误，说明不是整型的
        try:
            float(str)  # 用这个来验证，是不是浮点字符串
            return int(float(str))
        except ValueError:  # 如果报错，说明即不是浮点，也不是int字符串。   是一个真正的字符串
            return False
# 导入redis连接方法
from django_redis import get_redis_connection
# 使用默认配置连接到redis
cnn = get_redis_connection('default')
# 使用连接上的方法操作redis
cnn.hset('对象名'，'属性' ，'值')
"""


# 商品详情页面添加商品
def shopping(request):
    # 获取用户id,验证是否登录
    user_id = request.session.get("user_id")
    # print(user_id)
    if user_id is None:
        return JsonResponse({'age': 0, 'clue': '用户尚未登录'})

    # 获取商品id 获取商品数量
    number = request.POST.get('number')
    sku_id = request.POST.get('sku_id')
    # print(sku_id)

    # 获取商品数量
    try:
        number = int(number)
    except:
        return JsonResponse({'age': 1, 'clue': '数量未选择'})
    goods = Goods.objects.get(pk=sku_id)
    sku_num = goods.Goods_sku_Num
    # print(type(sku_num))
    # print(type(number))
    if number > sku_num:
        return JsonResponse({'age': 4, 'clue': '库存不足'})

    # 获取商品id
    try:
        sku_id = int(sku_id)
        Goods.objects.get(pk=sku_id)
    except Exception:
        return JsonResponse({'age': 2, 'clue': '商品不存在'})

    # 保存到数据库中, 设置
    user_id = "User_{}".format(user_id)
    cnn = get_redis_connection('default')
    cnn.hincrby(user_id, sku_id, number)
    return JsonResponse({'age': 3, 'clue': '添加购物车成功'})


# 商品分类页面添加商品
def showshopp(request):
    # 获取用户信息
    user_id = request.session.get("user_id")
    # print(user_id)
    if user_id is None:
        return JsonResponse({'age': 0, 'clue': '用户尚未登录'})

    # 获取商品id
    sku_id = request.POST.get('sku_id')

    # 设置商品数量
    number = request.POST.get('number')

    # 保存到数据库中, 设置
    user_id = "User_{}".format(user_id)
    cnn = get_redis_connection('default')
    cnn.hincrby(user_id, sku_id, number)

    # 判断数量是否为零
    new_num = cnn.hget(user_id, sku_id)
    if int(new_num) == 0:
        cnn.hdel(user_id, sku_id)

    # 获取商品总数
    all_num = cnn.hvals(user_id)
    start = 0
    for an in all_num:
        start += int(an)
    return JsonResponse({'age': 1, "all_num": start})


@old_request
def shopper(request):
    # 查询用户id
    user_id = request.session.get("user_id")
    user_id = "User_{}".format(user_id)
    # 建立连接
    cnn = get_redis_connection('default')
    # 获取商品信息
    # 获取数量
    over = cnn.hgetall(user_id)
    # print(over)
    # print(over)
    apple = over.items()
    # print(apple)
    list = []
    a = 0
    for key, value in apple:
        key = int(key)
        # cnn.hdel(user_id, key)
        apple = Goods.objects.get(pk=key)
        price = apple.Goods_sku_Price
        a += (int(price) * int(value))
        apple.count = value
        list.append(apple)
    context = {
        "goods": list,
        "price": a,
    }
    # return redirect("com:首页")
    return render(request, "shopping_trolley/shopcart.html", context)

templates/shopping_trolley/shopcart.html
{% extends 'father/index.html' %}
{% load static %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">购物车</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <!--购物车空的状态-->
    {% if goods %}
        <form action="{% url 'add:确认' %}" method="get" id="sumber">
            <ul class="shopcart-list">
                {% for good in goods %}
                    <li>
                        <label class="am-checkbox am-warning">
                            <input type="checkbox" name="sku_id" checked="checked" value="{{ good.pk }}" data-am-ucheck
                                   checked>
                        </label>
                        <a href="{% url 'com:详情' good.pk %}">
                            <img src="{{ MEDIA_URL }}{{ good.Goods_sku_Logo }}" class="shop-pic"/>
                        </a>
                        <div class="shop-list-mid">
                            <div class="tit">
                                <a href="{% url 'com:详情' good.pk %}">{{ good.Goods_spu_id.Goods_spu_name }}&emsp;{{ good.Goods_sku_name }}</a>
                            </div>
                            <b class="shop-list-price">￥<span class="price">{{ good.Goods_sku_Price }}</span></b>
                        </div>
                        <div class="list-cart1">
                            <div class="d-stock">
                                <a class="decrease">-</a>
                                <input readonly="" class="text_box num" name="" type="text" value="{{ good.count }}">
                                <span style="display:none">{{ good.pk }}</span>
                                <a class="increase">+</a>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </form>
    {% else %}
        <div class="login-logo">
            <img src="{% static 'images/care.png' %}">
            <p>亲、您的购物车还是空空的哦，快去装满它!</p>
            <a href="{% url 'com:首页' %}" class="goshopping">前去逛逛</a>
        </div>
    {% endif %}


    <div class="shop-fix">
        <label class="am-checkbox am-warning">
            <input type="checkbox" id="chack_all" checked="checked" value="" data-am-ucheck checked>
        </label>
        <a class="del">全选</a>
        <a href="javascript:" id="close" class="js-btn">去结算</a>
        <div class="js-text">
            <P>合计：<b id="one">{{ price }}</b></P>
            <p class="js-car">免费配送</p>
        </div>
        {% csrf_token %}
    </div>

{% endblock %}

{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'com:首页' %}" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'shop:购物车' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="{% url 'add:订单中心' %}" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:个人中心' %}" class="curr">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}

{#// parsint#}
{% block food_jss %}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                current_num += 1;
                self.siblings('input').val(current_num);
                {# 获取数量#}
                //设置数量
                var number = 1;
                //获取sku id;
                var sku_id = parseInt(self.siblings('span').html());
                console.debug(sku_id);
                var v2 = $("input[name='csrfmiddlewaretoken']").val();
                $.ajax({
                    type: 'post',
                    url: "{% url 'shop:商品页add' %}",
                    data: {"sku_id": sku_id, 'number': number, "csrfmiddlewaretoken": v2},
                    dataType: "json",
                    success: function (data) {
                        if (data.age == 0) {
                            var over = confirm("尚未登录,是否跳转登录页面");
                            if (over) {
                                location.href = "{% url 'user:登录' %}";  // ?next= url 'com:商店' id sku.pk
                            }
                        } else if (data.age == 1) {
                            talou_price()
                        }
                    }
                });
                //$("#one").text(price2.toFixed(2));
            });
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 0) {
                    current_num -= 1;
                    self.siblings('input').val(current_num);
                    {#  减少数量 #}
                    //设置数量
                    var number = -1;
                    //获取sku id;
                    var sku_id = parseInt(self.siblings('span').html());
                    //console.debug(sku_id);
                    var v2 = $("input[name='csrfmiddlewaretoken']").val();
                    $.ajax({
                        type: 'post',
                        url: "{% url 'shop:商品页add' %}",
                        data: {"sku_id": sku_id, 'number': number, "csrfmiddlewaretoken": v2},
                        dataType: "json",
                        success: function (data) {
                            if (data.age == 0) {
                                var over = confirm("尚未登录,是否跳转登录页面");
                                if (over) {
                                    location.href = "{% url 'user:登录' %}";  // ?next= url 'com:商店' id sku.pk
                                }
                            } else if (data.age == 1) {
                                talou_price()
                            }
                        }
                    });
                    if (current_num == 0) {
                        // 删除 empty(); $("p").parent(".selected"); $("p").remove(".hello");
                        self.parents("li").remove();
                    }
                }
            });

            function talou_price() {
                // 获取li里面的表单
                var checkbox = $(".shopcart-list").find(":checked");
                //初始价格0.00
                var new_price = 0;
                //遍历表单,获取指定数据
                $.each(checkbox, function (i, e) {
                    //获取父类li
                    var li = $(e).parents('li');
                    //获取li里面的价格,数量
                    var price = li.find(".price").text();
                    var number = li.find(".num").val();
                    new_price += price * number
                });
                $("#one").text(new_price.toFixed(2))
            }

            $("#chack_all").on('change', function () {
                //获取复选框状态
                var por = $(this).prop("checked");
                //console.debug(por)
                //更改商品复选框状态
                $(".shopcart-list").find(':checkbox').prop('checked', por);
                talou_price();
            });

            $(".shopcart-list").find(':checkbox').on('change', function () {
                //console.debug($(".shopcart-list").find(':checkbox').length == $(".shopcart-list").find(':checked').length);
                if ($(".shopcart-list").find(':checkbox').length == $(".shopcart-list").find(':checked').length) {
                    $("#chack_all").prop("checked", true);
                } else {
                    $("#chack_all").prop("checked", false);
                }
                talou_price();
            });

            //点击触发事件
            $("#close").on('click', function () {
                $("#sumber").submit()
            })
            //传送徐那种商品ID,数量
            //$("#close").on("click", function () {
            //    //console.debug(111);
            //    // 获取选中的商品,
            //    var number = $("li").find("input:checked");
            //    var v2 = $("input[name='csrfmiddlewaretoken']").val();
            //    var line = [];
            //    $.each(number, function (i, e) {
            //        //console.debug(e);
            //        var num = $(this).val();
            //        //var name = $(this).attr('name');
            //        //console.debug(name);
            //        //数组添加
            //        line.push(num)
            //    });
            //    //var id = line;
            //    //console.debug(id);
            //    $.ajax({
            //        type: 'get',
            //        url: "",
            //        traditional: true,
            //        data: {"sku_ids": line, "csrfmiddlewaretoken": v2},
            //        dataType: 'json',
            //        success: function (data) {
            //            console.debug(data.age)
            //        }
            //    });
            //})
        });
    </script>
{% endblock %}